name: release publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - name: Build
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: shadowJar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*
